### ISSUE TITLE
Utf8 File name

### ISSUE THREAD

**Issue by kalymnred** [jasperphp/JasperPHP#12]
Im using this package for a while without any problem. 
When I tried to change the name of the output file in UTF-8 format, i  encounter the following error.
"Exception in thread "main" net.sf.jasperreports.engine.JRRuntimeException: java.io.FileNotFoundException: /usr/share/testserver/documents/facture/??????0020/????????????.odt (No such file or directory)"
I am using php exec to call the executable within my application.

**Comment by kalymnred** [comment]
When you run your script via the CLI interface, the subprocess inherits its parent's environment, which contains the variable LANG, used to pass the encoding of the bytes to the underlying C runtime.

Likely when you execute your program via mod_php, LANG is not set. So you may succeed by configuring it yourself:

<?php
putenv('LANG=en_US.UTF-8');
exec(......

**Comment by FraGoTe** [comment]
did that solve your problem?

**Comment by pastrikosko-zz** [comment]
Yes!. you must set the enviroment variables before exetuting the comand if you dealing with uft8 filenames or foldernames..
